# cd/helm/helmv2.yml
# DYNAMIC MULTI-SERVICE + FULLY BACKWARD COMPATIBLE

include:
  - project: 'epay/devops/ci-templates'
    ref: main
    file: 'cd/helm/services.yml'

stages:
  - detect
  - generate
  - deploy
  - verify

variables:
  DEV_CLUSTER: "https://api.dev.sbiepay.sbi:6443"
  PREPROD_CLUSTER: "https://api.preprod.epay.sbi:6443"
  PREPROD_DC_CLUSTER: "https://api.dcpreprod.epay.sbi:6443"
  PROD_DR_CLUSTER: "https://api.dr.prod.epay.sbi:6443"
  PROD_DC_CLUSTER: "https://api.dc.prod.epay.sbi:6443"
  IMAGE_REGISTRY: "registry.dev.sbiepay.sbi:8443"
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

# ===================================================================
# 1. Detect ALL changed Helm charts (works on MR, push, commit, etc.)
# ===================================================================
detect_changed_charts:
  stage: detect
  image: ${IMAGE_REGISTRY}/library/rhelgit:latest
  script:
    - |
      set -eo pipefail
      git fetch --all --depth=300 || true

      if [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
        CHANGED_FILES=$(git ls-files)
      else
        CHANGED_FILES=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA)
      fi

      echo "Changed files:"
      echo "$CHANGED_FILES" | grep charts || true

      CHANGED_CHARTS=$(echo "$CHANGED_FILES" | \
        grep -E '^(dev|sit|uat|int|perf|pre-prod|pre-prod-dc|prod-dr|prod-dc)/charts/[^/]+/' | \
        sed -E 's|^(.*)/charts/([^/]+)/.*$|\1/\2|' | sort -u)

      if [ -z "$CHANGED_CHARTS" ]; then
        echo "NO_CHARTS_CHANGED=true" > skip.env
        echo "No Helm charts modified → skipping deployment"
        exit 0
      fi

      echo "Detected $(echo "$CHANGED_CHARTS" | wc -l) modified service(s):"
      echo "$CHANGED_CHARTS" | tee changed_charts.txt

      MATRIX=$(echo "$CHANGED_CHARTS" | awk -F'/' '
        {
          env = $1
          gsub(/-/, "_", env)
          service = $2
          printf "{\"env\":\"%s\",\"service\":\"%s\"},", env, service
        }' | sed 's/,$//')

      cat > matrix.json <<EOF
      [$MATRIX]
      EOF

      cat matrix.json | jq .
  artifacts:
    reports:
      dotenv: skip.env
    paths:
      - matrix.json
      - changed_charts.txt
    expire_in: 2h
  rules:
    - changes:
        - "**/charts/**/*"
      when: on_success
    - when: manual

# ===================================================================
# 2. Generate child pipeline with one job per changed service
# ===================================================================
generate_dynamic_pipeline:
  stage: generate
  image: alpine:latest
  needs:
    - job: detect_changed_charts
      artifacts: true
  script:
    - apk add --no-cache jq
    - |
      if grep -q "NO_CHARTS_CHANGED=true" skip.env 2>/dev/null; then
        echo "No charts changed → skipping child pipeline"
        exit 0
      fi

      cat > child-pipeline.yml <<'EOF'
      stages:
        - validate
        - deploy
        - verify

      include:
        - project: 'epay/devops/ci-templates'
          ref: main
          file: 'cd/helm/helmv2-dynamic.yml'
      EOF

      jq -r '.[] as $i |
        "deploy__\($i.env)__\($i.service):\n  extends: .deploy_one_service\n  variables:\n    ENV: \"\($i.env)\"\n    SERVICE_NAME: \"\($i.service)\"\n"' \
        matrix.json >> child-pipeline.yml

      echo "Generated $(jq length matrix.json) parallel deployment jobs"
      cat child-pipeline.yml
  artifacts:
    paths:
      - child-pipeline.yml
    expire_in: 2h

# ===================================================================
# 3. Trigger all deployments in parallel
# ===================================================================
trigger_deployments:
  stage: deploy
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate_dynamic_pipeline
    strategy: depend
  rules:
    - when: on_success

# ===================================================================
# 4. FALLBACK: Manual / Scheduled / Triggered deployment (100% unchanged)
# ===================================================================
include:
  - local: '/cd/helm/helmv2-dynamic.yml'

manual_deploy:
  extends: .deploy_one_service
  variables:
    ENV: $ENV
    SERVICE_NAME: $SERVICE_NAME
  rules:
    - if: '$SERVICE_NAME && $ENV'
      when: manual
    - when: never
